### ISSUE TITLE
Giving up the namespace

### ISSUE THREAD

**Issue by skbolton** [iamdustan/arbiter#3]
I have a node project that is an ORM for Salesforce that I am calling `arbiter-salesforce` how would you feel about giving up the name so I can just call it `arbiter`?

**Comment by iamdustan** [comment]
ooooh arbiter is such a good name too. You’re welcome to it, though I confess I’m a bit lazy to look up how to transfer it.

**Comment by skbolton** [comment]
I will add npm to this email chain.

What needs to happen to transfer the name to me @npm?

**Comment by skbolton** [comment]
Thanks @iamdustan I will be sure to credit and say thanks to you on the readme!
